const offersData = [
    {
        id: 1,
        image: 'media/oferta 1.png',
        alt: 'Oferta 1',
        price: 210900,
        sale: '32% OFF',
        delivery: true,
        svg: false,
    },
    {
        id: 2,
        image: 'media/oferta 2.png',
        alt: 'Oferta 2',
        price: 749990,
        sale: '25% OFF',
        delivery: true,
        svg: true,
    },
    {
        id: 3,
        image: 'media/oferta 3.png',
        alt: 'Oferta 3',
        price: 134950,
        sale: '50% OFF',
        delivery: true,
        svg: false,
    },
    {
        id: 4,
        image: 'media/oferta 4.png',
        alt: 'Oferta 4',
        price: 149900,
        sale: '30% OFF',
        delivery: true,
        svg: false,
    },
    {
        id: 5,
        image: 'media/oferta 5.png',
        alt: 'Oferta 5',
        price: 69990,
        sale: '17% OFF',
        delivery: false,
        svg: true,
    },
    {
        id: 6,
        image: 'media/oferta 6.png',
        alt: 'Oferta 6',
        price: 749990,
        sale: '25% OFF',
        delivery: true,
        svg: true,
    },
    {
        id: 7,
        image: 'media/oferta 7.png',
        alt: 'Oferta 7',
        price: 210900,
        sale: '32% OFF',
        delivery: true,
        svg: false,
    },
    {
        id: 8,
        image: 'media/oferta 8.png',
        alt: 'Oferta 8',
        price: 69990,
        sale: '17% OFF',
        delivery: false,
        svg: true,
    },
    {
        id: 9,
        image: 'media/oferta 9.png',
        alt: 'Oferta 9',
        price: 134950,
        sale: '50% OFF',
        delivery: true,
        svg: false,
    },
    {
        id: 10,
        image: 'media/oferta 10.png',
        alt: 'Oferta 10',
        price: 149900,
        sale: '30% OFF',
        delivery: true,
        svg: false,
    }
]

export {offersData}